### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by razvangoga** [tye-v2/tye2#2]
## technical

- [x] #12 update to .net 8
- [x] #12 update all references 
- [ ] replace all beta / old / obsolete refereces (ex : System.CommandLine 2.0.0-beta1.20104.2)
- [ ] a more user friendly configurations model
- [ ] more info about services in the dashboard (startup logs, used configs, conn strings / endpoints if any)

### non-technical

- [x] tye-v2/tye2#24
- [ ] #35
- [ ] #36

## nice to haves

- [ ] publish schema to schemastore #41 
- [ ] TBD ? 

## others

some good ideeas can be found here : 
- https://github.com/dotnet/tye/issues/1459
- https://github.com/miroslavpopovic/tye-and-docker-compose-samples
- https://gist.github.com/razvangoga/971767f1fa9c7684edbe2fbcaaa2db8e

**Comment by drakon660** [comment]
I would stay with those 

- [ ] update to .net 8
- [ ] update / replace all beta / old / obsolete refereces (ex : System.CommandLine 2.0.0-beta1.20104.2)
- [ ] super cool documentation like this : https://masstransit.io/documentation/concepts/messages

**Comment by razvangoga** [comment]
i would also add this : **_update and make available the schema for the yaml definition_**.

regarding the documentation - yes it looks way more usable than the bunch of Markdown files we have now. Can you find out on what engine the masstransit docs use?

**Comment by drakon660** [comment]
"update and make available" Could elaborate on that? I don't know what you mean. Yeah sure I will.

**Comment by razvangoga** [comment]
> "update and make available" Could elaborate on that? I don't know what you mean

see #13

**Comment by drakon660** [comment]
I see.

**Comment by drakon660** [comment]
This (update / replace all beta / old / obsolete refereces (ex : System.CommandLine 2.0.0-beta1.20104.2) is done.

**Comment by drakon660** [comment]
Maybe for version 0.12 which will be our first, I we shouldn't change so much in a code, we should deliver small parts. 
This command line is in beta2 stage but it doesn't mean that it is not working correctly.

**Comment by razvangoga** [comment]
i see the roadmap like this:

- v0.12 working published fork of tye (**_we have this, we just need to align the docs_**)
- v1 - a version with bigger / maybe breaking changes (given my limited time i would not forsee this dropping until the end of the year at least)

**Comment by razvangoga** [comment]
but the v0.12 roadmap issue is not this one but #1

**Comment by drakon660** [comment]
You are too pessimistic.

**Comment by drakon660** [comment]
I wrote to you, not more than 2 months ago, and you see how far we are despite the fact that we have jobs and so, more optimism.

**Comment by razvangoga** [comment]
in any case this roadmap is not set in stone, it was just my original idea as a followup version to v0.12 (we've done the update to dotnet 8 already).

some things in it (like **_a more user friendly configurations model_**) are quite complex (and unclear) to deserve a new version just for themselves

also missing are the removal of the **publish** and **deploy** parts - like i said when we first talked - i like aspire's publish model better where the tool generates some intermediate metadata file about the services, and some other tool / extension takes that and transpiles it to the format needed by some specific target (kubernetes, docker compose etc).

**Comment by drakon660** [comment]
In terms of roadmap we have to be flexible to deliver, regarding configuration model maybe we should create discussion, because I don't now what is on your mind. Publishing and deployment hmm, I don't think that there is a need to have another tool to do that especially tight coupled to .net world, but this is my private opinion.
